language: java
# 切换travis之前的构建环境（Ubuntu Trusty 14.04版本）oraclejdk8需要
#dist: trusty
jdk:
  - openjdk8

# 缓存
cache:
  directories:
    - '$HOME/.m2/repository'

# install安装，安装任何所需的依赖
install:
  - sh build.sh

# script脚本，运行构建脚本
script:
  - mvn test

# 指定分支，只有指定的分支提交时才会运行脚本
branches:
  only:
    - master